- build/classes/se/view/adminview/EditUsers.form
- build/classes/se/view/adminview/Register.form
- nbproject/private/private.properties
- src/se/view/adminview/EditUsers.form
- src/se/view/adminview/EditUsers.java
- src/se/view/adminview/Register.form
- src/se/view/adminview/Register.java
Register sidan + lite design ändringar i EditUser.
> EditUser, Register

- build/classes/se/view/AdminHome.form
- build/classes/se/view/AdminReporting.form
- src/se/view/AdminHome.form
- src/se/view/AdminHome.java
- src/se/view/AdminReporting.form
- src/se/view/AdminReporting.java
Finished AdminReporting interface.
> AdminReporting Interface

- src/se/database/QueryMethods.java
added methods for insert users
> created QueryMethods

- src/se/view/AdminEditUsers.java
Automatically displays the selected data inside the editor textbox
> AdminEditUsers display data

- build/classes/se/view/StartPage.form
- dist/README.TXT
- nbproject/project.properties
- src/se/database/QueryMethods.java
- src/se/view/StartPage.form
- src/se/view/StartPage.java
> login function

- build/classes/se/view/Admin.form
- src/se/view/Admin.form
- src/se/view/Admin.java
changed Repportering to Rapportering
> Fel bokstavering

- src/se/view/StartPage.form
- src/se/view/StartPage.java
> StartPage small fix

- src/se/view/Admin.java
- src/se/view/LibrarianView.form
- src/se/view/LibrarianView.java
- src/se/view/NewUserView.form
- src/se/view/NewUserView.java
> Fixat design

- src/se/view/AdminHomePage.form
- src/se/view/AdminHomePage.java
> AdminHomePage

- src/se/view/AddBook.form
- src/se/view/AddBook.java
- src/se/view/AdminHomePage.form
- src/se/view/AdminHomePage.java
- src/se/view/StartPage.form
- src/se/view/StartPage.java
> PasswordField

- src/se/view/AdminHomePage.form
- src/se/view/AdminHomePage.java
- src/se/view/StartPage.form
- src/se/view/StartPage.java
> email text ruta

- src/se/view/StartPage.java
> JtextField renamed

- src/se/database/QueryMethods.java
- src/se/model/Books.java
- src/se/model/E_Books.java
Functionality to add book and ebook objects to the database.
> Add Book/EBook

- src/se/database/QueryMethods.java
- src/se/model/LibraryCards.java
Klass LibraryCards och metod blockedCards  är skapade
> Klass LibraryCards och metod blockedCards

- src/se/database/QueryMethods.java
- src/se/model/LibraryCards.java
- src/se/view/LibrarianView.form
- src/se/view/LibrarianView.java
tillagd layout: knappen Spärrade Lånekort i LibrarianView
ändrade metoder: BlockedCards i QueryMethods,
jtbnBlockedCards i LibrarianView,
konstruktören i LibraryCards
> Spärrade Lånekort

- src/se/view/StartPage.form
- src/se/view/StartPage.java
- src/se/view/ViewBooks.form
- src/se/view/ViewBooks.java
Grunderna på layouten tillagda
> ViewBooks layout

- .gitignore
- test/se/database/MyConnectionTest.java
Har fixat en enkel unittest för MyConnection. I gitignore har jag accepterat Test Package.
> MyConnection Unit Test

- src/se/database/QueryMethods.java
- src/se/main/Main.java
- src/se/model/Books.java
- src/se/model/E_Books.java
Search books by title, author, category and isbn.
Search Ebooks by title, author and category
> Methods for searching books added to querymethods.

- src/se/database/QueryMethods.java
- src/se/model/Category.java
- src/se/view/AddBook.form
- src/se/view/AddBook.java
Fixed a bug in QueryMethods. Added a new method which finds all the categories in the database. Also fixed some issues with the AddBook GUI.
> Fixed AddBook

- src/se/database/QueryMethods.java
- src/se/view/AddBook.form
- src/se/view/AddBook.java
Categories are now saved with the Dewey decimal classification.
> Categories

- src/se/view/LibrarianView.form
- src/se/view/LibrarianView.java
- src/se/view/StartPage.form
- src/se/view/StartPage.java
Registreringsknappen tillagd på StartPage och några förfinningar på LibraryView
> Registreringsknapp + småfix

- src/se/view/LibrarianView.form
- src/se/view/LibrarianView.java
> librarian vy

- src/se/view/LibrarianView.form
- src/se/view/LibrarianView.java
Bibliotekarien kan se över lånade böcker  för specifika användare
> Besökaren rapport tillagd

- src/se/database/QueryMethods.java
- src/se/model/Books.java
- src/se/model/E_Books.java
- src/se/view/AddBook.form
- src/se/view/AddBook.java
Might need some changes in other methods where information is returned from the books/e-books tables.
> Add Object

- src/se/model/Seminarium.java
- src/se/view/SeminariumView.form
- src/se/view/SeminariumView.java
> Seminarium

- src/se/database/QueryMethods.java
- src/se/model/Seminar.java
- src/se/view/SeminarView.form
- src/se/view/SeminarView.java
Librarians can now register seminars.
> Register Seminar

- src/se/view/UserView.form
- src/se/view/UserView.java
> simon update vy Seminarium

- src/se/database/QueryMethods.java
- src/se/view/UserView.form
- src/se/view/UserView.java
Users can now book seminars through UserView.
> BookSeminar

- src/se/database/QueryMethods.java
Fixed the multiple connection issue that crashed the program.
> Updated QueryMethods

- src/se/view/LibrarianView.java
> Återställ användare

- src/se/view/AdminHomePage.form
- src/se/view/AdminHomePage.java
> AdminHomePage update

- src/se/view/AdminHomePage.java
Utlåningstabell fylld + lagertabell sök ikonen
> Tillägg på AdminView

- src/se/view/AdminHomePage.java
- src/se/view/NewUserView.form
- src/se/view/NewUserView.java
- src/se/view/StartPage.form
- src/se/view/StartPage.java
New Users can register in startpage
> Updaterat views

- src/se/view/LibrarianView.form
- src/se/view/LibrarianView.java
> Refactor LibrarianView

- src/se/database/QueryMethods.java
- src/se/view/NewUserView.java
- src/se/view/UserView.java
Funktionen Lägga till ny användare fanns så jag bara la till en rad för att skapa kort för nytt registrerade användare.
Jag fixade en bugg i getUserFullName() i UserView
> Registrera ny användare

- src/Services/DatabaseService.java
- src/se/model/Guest.java
- test/Services/JDBCDatabaseServiceImpIT.java
findGuestByMail
findGuests
findCategories
> Fixed Tests on:
